### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by orrmany**
I am trying to track your work, but I found I need to add some more .gitignore settings for local files

### CODE REVIEW

**Comment by cujomalainey** [comment]
I am good with the changes, but can you rebase the last two commits of your branch out of the request? They appear to be just to be a pull branch merge. They appear to cancel each other out which just confuses the history on the blame tool then.

**Comment by cujomalainey** [comment]
Also i will fix up my top commit and stop force pushing to make it easier for you to track my branches

**Comment by orrmany** [comment]
I will try, but currently I have no idea how to do that :D 
I need to educate myself first. :) I am newbie at git (I used RCS and ClearCase when I was actively developing for work)

**Comment by cujomalainey** [comment]
If you can't get it, I can merge it and rebase the commits out of the branch.

**Pull request closed without merging**
